-- No clue why this works but it does
ALTER TABLE User DROP FOREIGN KEY 'Post_ibfk_1';
DROP TABLE User;
ALTER TABLE Post DROP FOREIGN KEY 'PostCategory_ibfk_1';
DROP TABLE Post;
ALTER TABLE Category DROP FOREIGN KEY 'PostCategory_ibfk_2';
DROP TABLE Category;
DROP TABLE PostCategory;
ALTER TABLE TechStack DROP FOREIGN KEY 'UserTechStack_ibfk_2';
DROP TABLE TechStack;
DROP TABLE UserTechStack;
ALTER TABLE Comment DROP FOREIGN KEY 'CommentTag_ibfk_1';
DROP TABLE Comment;
DROP TABLE CommentTag;
DROP TABLE PostUpvote;
DROP TABLE CommentUpvote;
ALTER TABLE User DROP FOREIGN KEY 'Post_ibfk_1';
DROP TABLE User;
ALTER TABLE Post DROP FOREIGN KEY 'PostCategory_ibfk_1';
DROP TABLE Post;
ALTER TABLE Category DROP FOREIGN KEY 'PostCategory_ibfk_2';
DROP TABLE Category;
DROP TABLE PostCategory;
ALTER TABLE TechStack DROP FOREIGN KEY 'UserTechStack_ibfk_2';
DROP TABLE TechStack;
DROP TABLE UserTechStack;
ALTER TABLE Comment DROP FOREIGN KEY 'CommentTag_ibfk_1';
DROP TABLE Comment;
DROP TABLE CommentTag;
DROP TABLE PostUpvote;
DROP TABLE CommentUpvote;
DROP TABLE User;
DROP TABLE Post;
DROP TABLE User;
SELECT ' ' as '';
SELECT ' ' as '';
SELECT ' ' as '';
SELECT ' ' as '';
SELECT '<--------- Remaining Tables --------->' as '';
SHOW TABLES;
